### PR TITLE
pastaConfig

### PR DESCRIPTION
**Pull request by nastys**
Added pastaConfig, a cross-platform companion app for Pasta.
It supports GNU/Linux, OS X and Windows.
It is licensed under the GNU General Public License v3 or later.

Screenshot

### CODE REVIEW

**Comment by Syphurith** [comment]
@nastys @AlbertoSONIC I don't know which one we should use for configuration after.
There is `Pasta Configurator` already - .NET based, and may be also OK with **Mono**.
If not, a newly adjusted and compiled Executable would work, for all platforms that Mono supports.
This is Qt-based, and you need to compile for each platform.
All ok, the users choose which one to use. _BTW, I seemed to find two GPL licenses?_ And, i doubt should we include the binaries (those in `/build/`) - these could be compiled from source, and distributes in urls or attachments in forums, seperately. Git repo for developers, not best for hosting.
**Sorry if these words annoyed you**.. Feel free to contribute but be careful with your merges.

**Comment by nastys** [comment]
@Syphurith Sorry about that, you can remove the "builds" folder if you want, since I don't think this app needs to be updated frequently.
Pasta Configurator does not work very well with Mono (which needs to be installed, anyway), that's why I decided to make a cross-platform app.
I can compile it for all platforms at any time.

**Comment by Syphurith** [comment]
@nastys Many thanks to your reply. You can simply add `/pastaConfig/build` to `.gitignore`.
Eh, not very well with mono.. Ok.. _Any issues (like `unimplemented`, `unsupported`)?_

**Comment by nastys** [comment]
@Syphurith It does not detect the SD card (I can select it but it can't find Pasta). Also, it is not very convenient to run (you have to open a terminal and type "mono PastaCFW\ Configurator.exe").
It works with Wine, but you have to install Mono in Wine and also try to guess the letter assigned to the SD by Wine, which is hard and inconvenient, whereas pastaConfig is designed to work "out of the box" on any operating system, without installing anything.

**Comment by Syphurith** [comment]
For Qt based KDE, this app requires no installation. And for Gnome based environments, user would still have to install Qt runtime. Indeed both isn't so easy to deal.. _Eh.. a nodejs based one in terminal?_

**Comment by nastys** [comment]
@Syphurith On Ubuntu (and maybe other distros), Qt libraries are already installed.

**Comment by felipejfc** [comment]
I'ld prefer a python one, simpler, smaller, cross-compatible...
or java, your call.

I didnt like the qt solution for this matter

**Comment by nastys** [comment]
@felipejfc Windows users would need to install Python.

**Comment by felipejfc** [comment]
I know, and I think it is ok. Better than have to build the app for all the platforms.
If you use Qt either you statically link the libraries into your .exe or send the dll's needed for the app to run in the package, you end with 5MB zip

Installing python is less trouble than that

**Comment by felipejfc** [comment]
Also, take a look
http://www.py2exe.org/
https://github.com/pyinstaller/pyinstaller/wiki

**Comment by nastys** [comment]
@felipejfc A packaged Python app would take some space as well.

**Comment by Syphurith** [comment]
@felipejfc well i prefer a nodejs one - you can just distribute a standalone executable with it.
Still it would need a batch/shell file to execute.

**Comment by felipejfc** [comment]
nodejs purpose is not that, it is better suitable to webapps and services...

python is a better fit in this case.
@nastys less than qt

@Syphurith if you are up to making a nodejs one, feel free... I like this solution more than qt. If you end with a better solution than the current one I'll merge it.

Regards

**Comment by Syphurith** [comment]
@felipejfc yes that's it, leave user to choose which one to use.

**Comment by nastys** [comment]
Wouldn't it be better to add a configuration menu to Pasta itself?

**Comment by Syphurith** [comment]
Right.. that's the best one. would need to modify the routine.
However we've just removed the Menu from the loader.. Orz.

**Comment by nastys** [comment]
@Syphurith Can't we add a new button on the GUI? Or simply two checkboxes (Disable autoboot and Dump memory) and a label that says which was the last detected firmware?

**Comment by Syphurith** [comment]
@nastys what the button would be for?

**Comment by nastys** [comment]
@Syphurith "Options" or "Configuration"

**Comment by felipejfc** [comment]
I also like this option better, let the user configure inside pasta itself

**Comment by Syphurith** [comment]
I'm thinking of pasta identify the version itself, which user choose if auto-boot or dump ram.
However it would need a tiny text menu, and the identification function must not be incorrectly.

**Comment by nastys** [comment]
@Syphurith What version? Doesn't it already autodetect the firmware of the console?

**Comment by Syphurith** [comment]
It has a function that can auto-detect the console type (new 3ds or old 3ds). However no firmware auto-detection, and the function isn't called. So no auto-detection now indeed.

**Comment by Syphurith** [comment]
Oh i don't know the register location, so i forget to let it autodetect.

**Comment by nastys** [comment]
@Syphurith On my console it boots directly, and I didn't specify the version. Also, after boot, it set the first character of system.txt to 1 (fw. 4.x) automatically.

**Comment by Syphurith** [comment]
@nastys Oh? I didn't find anything related to auto-detection in the newest version of code.

**Comment by nastys** [comment]
@Syphurith I think it's in Brahma_Fork/source/main.c

**Comment by Syphurith** [comment]
@nastys You're right. So pasta only need two options. Oh well.

**Comment by nastys** [comment]
This is my idea:
bot-wchkbx
checkbox3

**Comment by felipejfc** [comment]
of course it would be better to better-position the buttons :p
@AlbertoSONIC what do you think?

**Comment by nastys** [comment]
Like this?
bot-wchkbx

**Comment by AlbertoSONIC** [comment]
I've planned to redraw the whole gui, I just need some time to do it! I already have a sketch!

**Comment by urherenow** [comment]
Why does the bottom left button say "Show GUI"? If you're looking at it, aren't you already seeing the GUI?

**Comment by Syphurith** [comment]
@urherenow Orz. That is it. @AlbertoSONIC Then what would it be like?

**Comment by nastys** [comment]
@urherenow There wasn't enough space for "Disable Autoboot" :P

**Comment by Syphurith** [comment]
@nastys Orz. Just something like `[ ] AutoBoot` might work. As below:
- [ ] AutoBoot

**Pull request merged**
