### PR TITLE
Port and update gfx and release scripts

### PR DESCRIPTION
**Pull request by nastys**
Summary of Changes:
- ported all shell scripts to Windows (release.bat requires devkitPro/ARM, ImageMagick and optionally 7-Zip or WinRAR)
- added chmod +x for pastaConfig and shell scripts in release.sh (impossible in Windows, maybe)
- added an argument to makeprev to specify the delay between frames of the generated gif files
- added high priority to the download of the template in makeprev.bat, should speed up the download of the template a bit

### CODE REVIEW

**Comment by Syphurith** [comment]
@nastys `chmod` call can not be easily implemented that's not so important luckily.
Eh.. Still that must be quite hard/uneasy to convert these. _I do similar things with nodejs..orz_

**Comment by nastys** [comment]
@Syphurith It's not been easy, but I've learnt a lot of sh and batch scripting.
Unfortunately, Node.js, Python and similar scripts require the interpreter to be installed in order to work :(
I know that it's possible to use Python to add the executable bit directly inside the zip and I'm going to try it as a workaround for Windows.

**Comment by Syphurith** [comment]
@nastys _If only use the core functionality that without any modules provided by 3rd-party, you can just use the `.exe` from dist.nodejs.org_ **without installation**. That's quite easier than Python on windows.
BTW I suggest there to be an **HTML5** version of the configuration tool. That would only need a browser.

**Comment by nastys** [comment]
@Syphurith The HTML5 Configurator would be awesome! But I'm not sure if it's possible to read the SD card and download firm.bin...

**Comment by Syphurith** [comment]
@nastys To my understanding it could create file and let users "download" it to somewhere.
For firm.bin, isn't it already reachable from browser? just a link would be ok.

**Comment by nastys** [comment]
@Syphurith So, the configurator would tell the user to "download and save this file to your SD/3ds/Pasta-CFW"? You might as well configure Pasta directly from its menu. As for the firm.bin downloading, it also needs some logical and AES operations that I doubt would be feasible by the browser itself, but maybe it's possible to add such functionality to Pasta itself.

**Comment by Syphurith** [comment]
@nastys Well.. All okey then. _Indeed, doing AES with browser is possible howeve a little tricky._

**Pull request merged**
