### PR TITLE
Revert "`.gitignore` and some file removed"

### PR DESCRIPTION
**Pull request by AlbertoSONIC**
Reverts capito27/Pasta-CFW#9

This is temporary, as this merge block me from commiting anything else. I'll add this commit again, after my required commit ;)

### CODE REVIEW

**Comment by Syphurith** [comment]
@AlbertoSONIC Oh well next time you can use `git rebase` to update the "start point" of your commits.
Still having problem in update the repo to main `HEAD` for me now.

**Comment by AlbertoSONIC** [comment]
Delete everything and clone again...

**Comment by Syphurith** [comment]
@AlbertoSONIC well i meant an unstable network. My repo wents well.

**Comment by AlbertoSONIC** [comment]
Oh ok! ;)

**Pull request merged**
